/**
 * PostManager.tsx — Client Component
 * Used by: /phase-7/mini-project/page.tsx
 *
 * WHAT THIS COMPONENT DOES:
 * ──────────────────────────
 * A full CRUD (Create, Read, Update, Delete) UI for blog posts.
 * All data changes happen in React state (no real database).
 *
 * FEATURES:
 * ──────────
 * - View a list of blog posts with published/draft status
 * - Add a new post (type title, click Add)
 * - Toggle published status (Draft ↔ Published)
 * - Edit post title inline (click Edit, modify, Save)
 * - Delete a post (with a confirmation step)
 *
 * WHY 'use client'?
 * ──────────────────
 * This component uses:
 *   - useState → to manage the post list, form input, editing state
 *   - Event handlers (onClick, onChange, onSubmit) → browser-only interactions
 * These APIs are NOT available in Server Components, so 'use client' is required.
 *
 * PRODUCTION EQUIVALENT:
 * ───────────────────────
 * In a real app with Prisma, each mutation would be a Server Action:
 *
 *   // app/phase-7/mini-project/actions.ts
 *   'use server';
 *   import { prisma } from '@/lib/prisma';
 *   import { revalidatePath } from 'next/cache';
 *
 *   export async function createPostAction(title: string) {
 *     await prisma.post.create({ data: { title, published: false, authorId: 1 } });
 *     revalidatePath('/phase-7/mini-project');
 *   }
 *
 *   export async function updatePostAction(id: number, data: Partial<Post>) {
 *     await prisma.post.update({ where: { id }, data });
 *     revalidatePath('/phase-7/mini-project');
 *   }
 *
 *   export async function deletePostAction(id: number) {
 *     await prisma.post.delete({ where: { id } });
 *     revalidatePath('/phase-7/mini-project');
 *   }
 *
 * In the component, you would replace the setState calls with:
 *   await createPostAction(newTitle);   // instead of setPosts([...])
 *   await updatePostAction(id, data);   // instead of setPosts(prev => map(...))
 *   await deletePostAction(id);         // instead of setPosts(prev => filter(...))
 */

"use client";

import { useState } from "react";

// ─── Types ─────────────────────────────────────────────────────────────────────
// In a real app, this type would be generated by Prisma or inferred by Drizzle.
// Example with Prisma: type Post = Prisma.PostGetPayload<{}>
// Example with Drizzle: type Post = typeof posts.$inferSelect
interface Post {
  id: number;
  title: string;
  published: boolean;
  createdAt: string; // ISO date string — in real app this would be a Date object
}

// ─── Props ─────────────────────────────────────────────────────────────────────
interface PostManagerProps {
  // initialPosts comes from the Server Component (page.tsx).
  // In a real app, this would be data fetched from the database at render time.
  // Here, it is the SEED_POSTS array from page.tsx.
  initialPosts: Post[];
}

// ─── PostManager Component ─────────────────────────────────────────────────────
export function PostManager({ initialPosts }: PostManagerProps) {
  // ── State ──────────────────────────────────────────────────────────────────
  // The main list of posts. Initialised with data from the Server Component.
  // In a real app: mutations would call Server Actions, then revalidatePath()
  // would trigger a re-render with fresh data from the DB.
  const [posts, setPosts] = useState<Post[]>(initialPosts);

  // The value of the "new post" title input
  const [newTitle, setNewTitle] = useState("");

  // Which post is currently being edited (null = no editing in progress)
  const [editingId, setEditingId] = useState<number | null>(null);

  // The current edited title value (shown in the inline edit input)
  const [editTitle, setEditTitle] = useState("");

  // ID of the post that has a delete confirmation showing (null = none)
  const [confirmDeleteId, setConfirmDeleteId] = useState<number | null>(null);

  // Simple filter: "all" | "published" | "draft"
  const [filter, setFilter] = useState<"all" | "published" | "draft">("all");

  // ── Derived state ──────────────────────────────────────────────────────────
  // Filter the posts list based on the selected filter.
  // This is NOT stored in state — it is computed from existing state.
  const filteredPosts = posts.filter((post) => {
    if (filter === "published") return post.published;
    if (filter === "draft") return !post.published;
    return true; // "all" — show everything
  });

  const publishedCount = posts.filter((p) => p.published).length;
  const draftCount = posts.filter((p) => !p.published).length;

  // ── CRUD Handlers ──────────────────────────────────────────────────────────

  /**
   * Add a new post.
   *
   * SIMULATION: appends to the posts state array.
   *
   * PRODUCTION EQUIVALENT:
   *   await createPostAction(newTitle);
   *   // Server Action calls: prisma.post.create({ data: { title: newTitle, published: false } })
   *   // Then: revalidatePath('/phase-7/mini-project') refreshes data from DB
   */
  function handleAddPost() {
    // Trim whitespace and reject empty titles
    const trimmed = newTitle.trim();
    if (!trimmed) return;

    // Build the new post object.
    // In a real DB, 'id' would be assigned by the database (autoincrement).
    // 'createdAt' would be set by the DB (@default(now())).
    // Here we simulate both with client-side values.
    const newPost: Post = {
      id: Date.now(), // Simulated ID — guaranteed unique within this session
      title: trimmed,
      published: false, // New posts start as drafts (same default as real schema)
      createdAt: new Date().toISOString().split("T")[0], // YYYY-MM-DD
    };

    // Prepend to the list so new posts appear at the top
    setPosts((prev) => [newPost, ...prev]);

    // Clear the input after adding
    setNewTitle("");
  }

  /**
   * Toggle a post between published and draft.
   *
   * SIMULATION: updates the matching post in the state array.
   *
   * PRODUCTION EQUIVALENT:
   *   await updatePostAction(id, { published: !post.published });
   *   // Server Action calls: prisma.post.update({ where: { id }, data: { published: !post.published } })
   */
  function handleTogglePublished(id: number) {
    setPosts((prev) =>
      prev.map((post) =>
        post.id === id ? { ...post, published: !post.published } : post
      )
    );
  }

  /**
   * Start editing a post title.
   * Pre-fills the edit input with the current title.
   */
  function handleStartEdit(post: Post) {
    setEditingId(post.id);
    setEditTitle(post.title);
    // Close any open delete confirmation to keep UI clean
    setConfirmDeleteId(null);
  }

  /**
   * Save the edited title.
   *
   * SIMULATION: updates the matching post in the state array.
   *
   * PRODUCTION EQUIVALENT:
   *   await updatePostAction(editingId, { title: editTitle.trim() });
   *   // Server Action calls: prisma.post.update({ where: { id: editingId }, data: { title } })
   */
  function handleSaveEdit() {
    const trimmed = editTitle.trim();
    if (!trimmed || editingId === null) {
      // Empty title → cancel edit without saving
      setEditingId(null);
      return;
    }

    setPosts((prev) =>
      prev.map((post) =>
        post.id === editingId ? { ...post, title: trimmed } : post
      )
    );

    // Exit editing mode
    setEditingId(null);
    setEditTitle("");
  }

  /**
   * Cancel edit without saving.
   */
  function handleCancelEdit() {
    setEditingId(null);
    setEditTitle("");
  }

  /**
   * Show the delete confirmation for a specific post.
   * Two-step delete prevents accidental data loss.
   */
  function handleAskDelete(id: number) {
    setConfirmDeleteId(id);
    // Exit any active editing to keep UI clean
    setEditingId(null);
  }

  /**
   * Confirm and execute the delete.
   *
   * SIMULATION: filters the post out of the state array.
   *
   * PRODUCTION EQUIVALENT:
   *   await deletePostAction(confirmDeleteId);
   *   // Server Action calls: prisma.post.delete({ where: { id: confirmDeleteId } })
   */
  function handleConfirmDelete(id: number) {
    setPosts((prev) => prev.filter((post) => post.id !== id));
    setConfirmDeleteId(null);
  }

  /**
   * Cancel the delete confirmation without deleting.
   */
  function handleCancelDelete() {
    setConfirmDeleteId(null);
  }

  // ── Keyboard support ───────────────────────────────────────────────────────
  // Allow pressing Enter in the new post input to trigger Add
  function handleNewTitleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") handleAddPost();
  }

  // Allow pressing Enter to save edit, Escape to cancel
  function handleEditKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") handleSaveEdit();
    if (e.key === "Escape") handleCancelEdit();
  }

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div className="space-y-6">

      {/* ── Stats bar ──────────────────────────────────────────────────────── */}
      {/*
       * Shows a quick count of total / published / draft.
       * These are derived from the posts state — no extra state needed.
       */}
      <div className="flex flex-wrap gap-3">
        {[
          { label: "Total",     count: posts.length,   color: "border-white/10 text-gray-300" },
          { label: "Published", count: publishedCount, color: "border-green-500/30 text-green-400" },
          { label: "Drafts",    count: draftCount,     color: "border-yellow-500/30 text-yellow-400" },
        ].map((stat) => (
          <div
            key={stat.label}
            className={`rounded-lg border px-3 py-1.5 text-xs font-medium ${stat.color}`}
          >
            <span className="font-mono font-bold">{stat.count}</span>
            <span className="ml-1.5 text-gray-500">{stat.label}</span>
          </div>
        ))}
      </div>

      {/* ── Add Post Form ───────────────────────────────────────────────────── */}
      {/*
       * A simple title input + Add button.
       * Press Enter or click Add to create the post.
       *
       * In a production app, this would be a <form action={createPostAction}>
       * — a native HTML form that calls a Server Action when submitted.
       */}
      <div className="rounded-xl border border-white/10 bg-white/2 p-4">
        <p className="text-xs text-gray-500 mb-3 font-medium uppercase tracking-wide">
          Add New Post
        </p>
        <div className="flex gap-2">
          <input
            type="text"
            placeholder="Post title..."
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
            onKeyDown={handleNewTitleKeyDown}
            className="flex-1 bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-blue-500/50 transition-colors"
            aria-label="New post title"
          />
          <button
            onClick={handleAddPost}
            disabled={!newTitle.trim()}
            className="bg-blue-600 hover:bg-blue-500 disabled:opacity-40 disabled:cursor-not-allowed text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
          >
            Add
          </button>
        </div>
        <p className="text-xs text-gray-600 mt-2">
          {/* Explain what would happen in production — key learning point */}
          Production: this would call a Server Action →{" "}
          <code className="text-gray-500">prisma.post.create(&#123; data: &#123; title &#125; &#125;)</code>
        </p>
      </div>

      {/* ── Filter Tabs ─────────────────────────────────────────────────────── */}
      <div className="flex gap-2" role="group" aria-label="Filter posts">
        {(["all", "published", "draft"] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`text-xs px-3 py-1.5 rounded-full border transition-colors capitalize ${
              filter === f
                ? "bg-blue-600 border-blue-500 text-white"
                : "border-white/10 text-gray-400 hover:border-white/30 hover:text-gray-300"
            }`}
            aria-pressed={filter === f}
          >
            {f}
          </button>
        ))}
      </div>

      {/* ── Post List ───────────────────────────────────────────────────────── */}
      {filteredPosts.length === 0 ? (
        <div className="rounded-xl border border-white/10 bg-white/2 p-8 text-center">
          <p className="text-gray-500 text-sm">
            {filter === "all"
              ? "No posts yet. Add one above!"
              : `No ${filter} posts.`}
          </p>
        </div>
      ) : (
        <div className="space-y-2">
          {filteredPosts.map((post) => (
            <div
              key={post.id}
              className={`rounded-xl border p-4 transition-colors ${
                post.published
                  ? "border-green-500/20 bg-green-500/5"
                  : "border-white/10 bg-white/2"
              }`}
            >
              {editingId === post.id ? (
                // ── Inline Edit Mode ─────────────────────────────────────────
                <div className="flex gap-2 items-center">
                  <input
                    type="text"
                    value={editTitle}
                    onChange={(e) => setEditTitle(e.target.value)}
                    onKeyDown={handleEditKeyDown}
                    autoFocus
                    className="flex-1 bg-black/40 border border-blue-500/50 rounded-lg px-3 py-1.5 text-sm text-gray-200 focus:outline-none"
                    aria-label="Edit post title"
                  />
                  <button
                    onClick={handleSaveEdit}
                    className="text-xs bg-blue-600 hover:bg-blue-500 text-white px-3 py-1.5 rounded-lg transition-colors"
                  >
                    Save
                  </button>
                  <button
                    onClick={handleCancelEdit}
                    className="text-xs text-gray-500 hover:text-gray-300 px-3 py-1.5 rounded-lg transition-colors"
                  >
                    Cancel
                  </button>
                </div>
              ) : confirmDeleteId === post.id ? (
                // ── Delete Confirmation Mode ──────────────────────────────────
                // Two-step delete prevents accidental deletion
                <div className="flex items-center gap-3">
                  <p className="text-sm text-red-300 flex-1">
                    Delete &quot;{post.title}&quot;? This cannot be undone.
                  </p>
                  <button
                    onClick={() => handleConfirmDelete(post.id)}
                    className="text-xs bg-red-600 hover:bg-red-500 text-white px-3 py-1.5 rounded-lg transition-colors"
                  >
                    Delete
                  </button>
                  <button
                    onClick={handleCancelDelete}
                    className="text-xs text-gray-500 hover:text-gray-300 px-3 py-1.5 rounded-lg transition-colors"
                  >
                    Cancel
                  </button>
                </div>
              ) : (
                // ── Normal Display Mode ───────────────────────────────────────
                <div className="flex items-start gap-3">
                  {/* Post info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      {/* Title */}
                      <h3 className="text-sm font-medium text-white truncate">
                        {post.title}
                      </h3>
                      {/* Published / Draft badge */}
                      <span
                        className={`shrink-0 text-xs px-2 py-0.5 rounded-full border ${
                          post.published
                            ? "border-green-500/30 text-green-400 bg-green-500/10"
                            : "border-yellow-500/30 text-yellow-500 bg-yellow-500/10"
                        }`}
                      >
                        {post.published ? "Published" : "Draft"}
                      </span>
                    </div>
                    {/* Date — in a real app this would be formatted from a Date object */}
                    <p className="text-xs text-gray-600 font-mono">{post.createdAt}</p>
                  </div>

                  {/* Action buttons */}
                  <div className="flex gap-1.5 shrink-0">
                    {/*
                     * Toggle Published button
                     * SIMULATION: calls handleTogglePublished() → updates state
                     * PRODUCTION: would call updatePostAction(id, { published: !post.published })
                     *             → prisma.post.update({ where: { id }, data: { published } })
                     */}
                    <button
                      onClick={() => handleTogglePublished(post.id)}
                      title={post.published ? "Move to Draft" : "Publish"}
                      className="text-xs text-gray-400 hover:text-white border border-white/10 hover:border-white/30 px-2 py-1 rounded-lg transition-colors"
                    >
                      {post.published ? "Unpublish" : "Publish"}
                    </button>

                    {/*
                     * Edit button
                     * Switches the row into inline edit mode.
                     * PRODUCTION: would call updatePostAction(id, { title: editTitle })
                     *             → prisma.post.update({ where: { id }, data: { title } })
                     */}
                    <button
                      onClick={() => handleStartEdit(post)}
                      title="Edit title"
                      className="text-xs text-gray-400 hover:text-blue-400 border border-white/10 hover:border-blue-500/40 px-2 py-1 rounded-lg transition-colors"
                    >
                      Edit
                    </button>

                    {/*
                     * Delete button (first click shows confirmation)
                     * PRODUCTION: would call deletePostAction(id)
                     *             → prisma.post.delete({ where: { id } })
                     */}
                    <button
                      onClick={() => handleAskDelete(post.id)}
                      title="Delete post"
                      className="text-xs text-gray-400 hover:text-red-400 border border-white/10 hover:border-red-500/40 px-2 py-1 rounded-lg transition-colors"
                    >
                      Delete
                    </button>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* ── Production Notes ─────────────────────────────────────────────────── */}
      {/*
       * This section is purely educational — it reminds the learner of the
       * two key differences between this simulation and a real production app.
       */}
      <div className="rounded-xl border border-white/10 bg-white/2 p-4">
        <p className="text-xs text-gray-500 mb-2 font-medium uppercase tracking-wide">
          In a Real Production App...
        </p>
        <ul className="space-y-1.5 text-xs text-gray-500">
          <li className="flex gap-2">
            <span className="text-blue-400 shrink-0">1.</span>
            Each Add/Edit/Delete button calls a{" "}
            <code className="text-gray-400">Server Action</code> instead of updating state
          </li>
          <li className="flex gap-2">
            <span className="text-blue-400 shrink-0">2.</span>
            The Server Action calls{" "}
            <code className="text-gray-400">prisma.post.create/update/delete</code> (or Drizzle/Supabase equivalent)
          </li>
          <li className="flex gap-2">
            <span className="text-blue-400 shrink-0">3.</span>
            After the mutation,{" "}
            <code className="text-gray-400">revalidatePath()</code> invalidates the cache so the
            Server Component re-fetches fresh data from the DB
          </li>
          <li className="flex gap-2">
            <span className="text-blue-400 shrink-0">4.</span>
            Data persists across page refreshes, browser restarts, and all users see the same posts
          </li>
        </ul>
      </div>
    </div>
  );
}
